openapi: 3.0.0
info:
  version: 1.0.0
  title: eGov Property Assessment System.
  description: | 
    The assement of the property is applicable for one financial year. 
    * Create new assessment for an existing property
    * Update existing assessment details
    * Search assessments based on the criteria
  contact:
    name: Egovernments Foundation
    email: contact@egovernments.org
x-module: PT
x-common-path: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml'
paths:
  /assessment/_create:
    post:
      summary: Creates assessment for an property into the system.
      description: API to create assessment for the given propertyid and financialYear. Creating assessment will result in generation of demand for the given financial year
      x-roles: 'PT_CEMP,CITIZEN'
      responses:
        '201':
          description: Prroperty Assessed sucessfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AssessmentResponse'
        '400':
          description: Failed to process the request
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml#/components/schemas/ErrorRes'
      tags:
        - Assessment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssessmentRequest'
        description: Details for the new assessment + RequestHeader meta data.
        required: true
  /assessment/_update:
    post:
      summary: Updates existing assessment.
      description: The update API is used to reassess the property for the given financial year. Updating assessment will update the demand for the given financial year
      x-roles: 'PT_CEMP,CITIZEN'
      tags:
        - Assessment
      responses:
        '200':
          description: Assessment details updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AssessmentResponse'
        '400':
          description: Failed to update Assessment details
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml#/components/schemas/ErrorRes'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssessmentRequest'
        description: Request header for the assessment Request.
        required: true
  /assessment/_search:
    post:
      summary: Get the list of assessment defined in the system.
      description: |
        Get the assessment list based on the input parameters.
      x-roles: 'PT_CEMP,CITIZEN'
      parameters:
        - $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml#/components/parameters/tenantId'
        - name: propertyIds
          in: query
          description: List of system generated ids of properties.
          required: false
          schema:
            type: array
            items:
              type: string
        - name: assessmentNumbers
          in: query
          description: List of system assessment ids of properties.
          required: false
          schema:
            type: array
            items:
              type: string
        - name: financialYear
          in: query
          description: The financial Year of the assessment
          required: false
          schema:
            type: string
            format: varchar

      responses:
        '200':
          description: Successful response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AssessmentResponse'
        '400':
          description: Invalid input.
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml#/components/schemas/ErrorRes'
      tags:
        - Assessment
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml#/components/schemas/RequestHeader'
        description: RequestHeader meta data.
        required: true
  /assessment/_delete:
    post:
      summary: Delete existing assessment details
      description: Deletes  assessment detials  based on assessment number from the system.
      x-roles: PT_ADMIN
      tags:
        - Assessment
      responses:
        '200':
          description: deleted assessment successful
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AssessmentResponse'
        '404':
          description: Assessment details not found
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml#/components/schemas/ErrorRes'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssessmentRequest'
        description: Request header for the assessment Request.
        required: true
  /assessment/_cancel:
    post:
      summary: Deactivates/Cancels existing assessment.
      description: Deactivates/Cancels based on the given assessment number
      x-roles: PT_ADMIN
      tags:
        - Assessment
      responses:
        '200':
          description: Deactivates/Cancels assessment successful
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AssessmentResponse'
        '400':
          description: Deactivation of assessment failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml#/components/schemas/ErrorRes'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssessmentRequest'
        description: Request header for the assessment cancel/deactivate Request.
        required: true
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'https://virtserver.swaggerhub.com/egovernmets-faoundat/PT-2.0/1.0.0'
  - url: 'https://egov-micro-dev.egovernments.org'
components:
  schemas:
    Assessment:
      type: object
      description: Contains the assessment details of a property. Assessment refers to the calculation of  property tax for the given property id and financial year
      properties:
        id:
          type: string
          description: Unique UUID for the transaction  
          minLength: 2
          maxLength: 64
          readOnly: true
        tenantId:
          type: string
          description: Unique identifier of the ULB(City)
          minLength: 2
          maxLength: 64
        assessmentNumber:
          type: string
          description: The formatted number generated by the system for the given assessment details.
          minLength: 2
          maxLength: 64
          readOnly: true
        propertyId:
          type: string
          description: | 
           The propertyId against which assessment is done. Below is the referance for the property registry contract.
           "https://raw.githubusercontent.com/egovernments/municipal-services/property-contracts/docs/property-services/property-service-contracts/property-registry-v1.0.0.yaml#/components/schemas/Property"
          minLength: 2
          maxLength: 64
        financialYear:
          type: string
          description: The financialYear of the assessmnet
          minLength: 2
          maxLength: 16
        demandId:
          type: string
          description: Id of the demand, against which bill will be generated.
          readOnly: true
        additionalDetails:
          type: object
          description: Json object to capture any extra information which is not accommodated of model
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
            - CANCELED
        auditDetails:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml#/components/schemas/AuditDetails'
      required:
        - tenantId
        - propertyId
        - financialYear
    AssessmentRequest:
      description: The request to create or update an assessment. Contains the RequestHeader and the assessment details
      properties:
        RequestHeader:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml#/components/schemas/RequestHeader'
        Assessment:
          $ref: '#/components/schemas/Assessment'
    AssessmentResponse:
      description: The response of create or update of assessment. Contains the ResponseHeader and created/updated assessment
      properties:
        RequestHeader:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/PT_APPLY_PAY/docs/common/contracts/v1-1-1.yml#/components/schemas/ResponseHeader'
        Assessment:
          type: array
          items:
            $ref: '#/components/schemas/Assessment'
